language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - nosetests --with-coverage --cover-package=app  && coverage report

after_success:
  - coveralls
  - codecov --

cache: pip
